### ISSUE TITLE
Error 400 when attempting to use

### ISSUE THREAD

**Issue by willuhmjs** [GuillaumeFalourd/copy-push-files#1]
I am trying to push a file from one org repo to another. I have the `access_token` key set in the organization secrets for Actions. This is what my workflow looks like:

```
name: Transfer README
on: 
  push:
    branches: [ main ]
    paths: [ "README.md" ] 
  workflow_dispatch:

jobs:
  transfer-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Execute Transfer 🚀
        uses: GuillaumeFalourd/copy-push-files@v1
        with:
          source_files: README.md
          remote_repository: "https://github.com/lifecharities/.github"
          commit_message: Update README
          target_dir: profile
          access_token: ${{ secrets.ACCESS_TOKEN }}
```

[Here](https://github.com/lifecharities/lifecharities.github.io/runs/5109767152?check_suite_focus=true) is a link to the action log.
